### ISSUE TITLE
[Suggestion] Bluetooth Low Energy SDK

### ISSUE THREAD

**Issue by carallo** [theScrabi/CoraLibre-android-sdk#5]
Hi,

I don't know if this might be of any use, I just wanted to point out in case it could be useful.
The french StopCOVID app is Play Services independent, it doesn't use the Exposure Notification API, so maybe you could find some useful code in there:

[Bluetooth Low Energy SDK for Android](https://gitlab.inria.fr/stopcovid19/stopcovid-blesdk-android)

**Comment by theScrabi** [comment]
Is that app compatible with the [Apple/Google](https://www.apple.com/covid19/contacttracing/) protocol? That would be the important part.

**Comment by carallo** [comment]
Unfortunatly it seems not, see [GitLab issue](https://gitlab.inria.fr/stopcovid19/stopcovid-android/-/issues/34) :(

**Comment by carallo** [comment]
An update on that [issue](https://gitlab.inria.fr/stopcovid19/stopcovid-android/-/issues/34) seem to state that the french implementation is indeed compatible with the Apple/Google protocol:

> Today, 18 countries in Europe use Exposure Notification API for their apps, following European vote from April 17.
It will probably use specifications provided by Apple / Google on April: these specifications were used to implement open-source Raspberry Pi version of Exposure Notification API.

> Apple is blocking implementations of Exposure Notification API on common apps since iOS 13.4 / iOS 13.5 due to security reasons. Common apps can access to GPS, not Exposure Notification apps. So, if an app integrate an "home made" Exposure Notification API, it can scan bluetooth and use geolocation to identify users.

> But StopCovid is said to be compatible with Exposure Notification. Perhaps a breach on iOS or a bypass provided by Apple. Will probably be revealed soon.
